postgres:
  password: "secure-db-password-99"

artifactory:
  enabled: true
  dockerConfigJson: ""

frontend:
  replicaCount: 2
  image:
    repository: "my-jfrog-artifactory.duckdns.org/docker-local/frontend"
    tag: "latest"

taskService:
  replicaCount: 2
  image:
    repository: "my-jfrog-artifactory.duckdns.org/docker-local/task-service"
    tag: "latest"

quoteService:
  replicaCount: 1
  image:
    repository: "my-jfrog-artifactory.duckdns.org/docker-local/quote-service"
    tag: "latest"

newrelic:
  licenseKey: ""
