{{- if and .Values.artifactory.enabled .Values.artifactory.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.artifactory.dockerConfigJson }}
{{- end }}
