apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
spec:
  replicas: {{ .Values.quoteService.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      imagePullSecrets:
        - name: artifactory-docker-secret
      containers:
        - name: quote-service
          image: "{{ .Values.quoteService.image.repository }}:{{ .Values.quoteService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/newrelic/newrelic.jar"
            - name: NEW_RELIC_APP_NAME
              value: "quote-service"
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-secrets
                  key: license-key
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: quote-service
