apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/name: db-secret
    app.kubernetes.io/part-of: java-app
type: Opaque
stringData:
  postgres-password: "postgres-secure-password-123!"
