---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: gitops-control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: java-app-gitops
  labels:
    name: java-app-gitops
    environment: gitops-workload
